wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707406477.34362
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.7
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
n_neighbors:
  desc: null
  value: 15
p:
  desc: null
  value: 3
weights:
  desc: null
  value: uniform
